### ISSUE TITLE
Pystache not following spec for dictionaries?

### ISSUE THREAD

**Issue by larsks** [defunkt/pystache#150] opened 2013-09-01 04:38 UTC
Based on the "Non-False Values" section of `mustache(5)`...

> Non-False Values
> 
> When the value is non-false but not a list, it will be used as the context for a single 
> rendering of the block.

I figured that given this dictionary:

```
session = {
  'visited': True,
   '_accessed_time': 1378009889.819518, 
  '_creation_time': 1378009571.726927,
}
```

And this template:

```
{{#session}}
Value of `visited`: {{visited}}
{{/session}}
```

And rendering it like this:

```
pystache.render(template, { 'session': session })
```

That it would expand `{{visited}}` to `True`...but it appears to be
treating `{{#session}}` as a _list_, and is iterating over the keys.
Am I misreading the _mustache_ documentation, or is _pystache_ not
conforming?

Thanks!

**Comment by cjerdonek** [comment] 2013-09-01 17:59
What version of Pystache are you using?  I get the following when I run from the development branch:

```
Value of `visited`: True
```

**Comment by cjerdonek** [comment] 2013-09-01 18:02
PS - you should also check out this [Mustache spec](https://github.com/mustache/spec) because it has a more up-to-date and accurate description of how Pystache behaves.  My understanding is that `mustache(5)` is a lot older and doesn't describe all the features that Pystache supports, etc.

**Comment by cjerdonek** [comment] 2013-09-15 17:10
I'm closing this since I couldn't reproduce it and didn't receive any response from the original poster after a couple weeks.

**Closed as completed by cjerdonek** 2013-09-15 17:10 UTC
