### ISSUE TITLE
Trunk sometimes escapes list blocks for no reason

### ISSUE THREAD

**Issue by nickretallack** [defunkt/pystache#25] opened 2011-06-15 23:50 UTC
Every list block except the first one in the template has its contents escaped.  

```
>>> pystache.render("<p>{{#this}}<p>{{/this}}<p>{{#that}}<p>{{/that}}<p>{{#other}}<p>{{/other}}<p>", {'this':[1,2], 'that':[1,2], 'other':[1,2]})
Markup(u'<p><p><p><p>&lt;p&gt;&lt;p&gt;<p>&lt;p&gt;&lt;p&gt;<p>')
```

You can't get the error by repeating the same block though: if it renders unescaped the first time, it will do the same thing the second time, and visa versa.

```
>>> pystache.render("<p>{{#this}}<p>{{/this}}<p>{{#that}}<p>{{/that}}<p>{{#this}}<p>{{/this}}<p>{{#that}}<p>{{/that}}", {'this':[1,2], 'that':[1,2]})
Markup(u'<p><p><p><p>&lt;p&gt;&lt;p&gt;<p><p><p><p>&lt;p&gt;&lt;p&gt;')
```

The error does not occur at tag 3.1.  Just thought I'd make you guys aware of this.

**Comment by nickretallack** [comment] 2011-06-16 00:05
Used git bisect to locate the commit that breaks it.  75254d671adcf0cbc56a9c86cb831d6b5a7676dc.  Revert it and everything's peachy.

**Comment by drewp** [comment] 2011-10-03 02:50
Alternate example that breaks similarly, and is fixed by that revert (thanks, nickretallack!):

```
In [14]: render("{{#other}}{{{y}}}{{/other}} {{#x}}{{{thumb}}}{{/x}}", dict(other=dict(y="<hr>"), x=[dict(thumb="<b>one</b>"), dict(thumb="<b>two</b>")]))
Out[14]: Markup(u'<hr> &lt;b&gt;one&lt;/b&gt;&lt;b&gt;two&lt;/b&gt;')
```

```
after revert:
In [5]: render("{{#other}}{{{y}}}{{/other}} {{#x}}{{{thumb}}}{{/x}}", dict(other=dict(y="<hr>"), x=[dict(thumb="<b>one</b>"), dict(thumb="<b>two</b>")]))
Out[5]: u'<hr> <b>one</b><b>two</b>'
```

**Comment by cjerdonek** [comment] 2011-12-20 13:47
It looks like this is the same as issue #53, which was just closed.  It has been fixed in the development branch (with a unit test case added).  I also confirmed that your examples don't work in master but work correctly in the development branch.

Thanks for your patience!

**Closed as completed by cjerdonek** 2011-12-20 13:47 UTC
