### ISSUE TITLE
Allow None context value to render as empty string

### ISSUE THREAD

**Issue by sontek** [defunkt/pystache#130] opened 2012-08-14 15:40 UTC
If I pass an object with a None value in pystache and call it {{ name }}, it returns "None"    if I have a value in mustache and call it, I get ''.   This is resulting in inconsistent rendering dependent on if my template is coming from client side or server side.

What is the best way to handle this?

**Comment by sontek** [comment] 2012-08-14 17:39
The spec also seems to agree that it should return empty string, not None:
https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L106

**Comment by sontek** [comment] 2012-08-14 17:55
I made a pull request that fixes this for me but not sure if it was the correct way to implement it ( #131 )

**Comment by cjerdonek** [comment] 2012-08-15 11:11
> If I pass an object with a None value in pystache and call it {{ name }}, it returns "None"

This is by design.  For example, the spec says [this](https://raw.github.com/mustache/spec/master/specs/interpolation.yml)--

"This tag's content names the data to replace the tag...  Data should be coerced into a string (and escaped, if appropriate) before interpolation."

And in Python--

```
>>> str(None)
'None'
```

There is even a test to check this behavior [here](https://github.com/defunkt/pystache/blob/893bd6ae0d6b2c8c66515496642795e9d82bfce1/pystache/tests/test_renderengine.py#L230) (alongside tests for other falsey values like `0` and `False`).

> This is resulting in inconsistent rendering dependent on if my template is coming from client side or server side.

It is a known issue that different implementations of Mustache treat "falsey" values differently.  For example, see the thread for [this issue](https://github.com/mustache/spec/issues/28).

> What is the best way to handle this?

If you want something to render as the empty string, my advice would be to explicitly give it a value of the empty string rather than `None`.  Would that work for you?

**Comment by cjerdonek** [comment] 2012-08-15 11:19
> The spec also seems to agree that it should return empty string, not None:
> https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L106

If you read the text, it says, "Failed context lookups should default to empty strings."  There is a difference between a key not being found (a failed lookup) versus a key having a value of `None`.  If you try a missing key, I think you'll find that it works by returning an empty string.  Indeed, it should because Pystache runs all of the spec tests (including the one you're quoting here) as part of its unit test suite!

**Comment by sontek** [comment] 2012-08-15 15:00
It wouldn't make sense to set these values as empty strings because they are None/null, they haven't had a value set.   I just want it to be consistent so that I can use mustache.js or pystache and get the same template back.  There really is no point in having different implementations of the language if they aren't going to try to return the same results.

**Comment by cjerdonek** [comment] 2012-08-15 15:18
Are you using the "dictionary" or "object" form of context?

> It wouldn't make sense to set these values as empty strings because they are None/null, they haven't had a value set.

And yet you are setting the value to be None.  As I said above, there is a difference between a context key not being present and a context key being present with value None.  Why not remove the key if there is no value?  Otherwise, setting None values to the empty string seems like a small price for you to have rendering consistency.

To insist that different Mustache implementations have the same behavior on booleans, null, None, etc. is a losing battle because they're already different.  That's just the way Mustache is.  See the thread I referred you to above for a taste of that.

Maybe we can expose the ability to have booleans, None, etc. render differently through the API somehow (e.g. by allowing a certain method to be overridden or by injecting a class, etc).

**Comment by cjerdonek** [comment] 2012-08-15 15:24
I will think about allowing this aspect of behavior to be customized, but it may take some time.

**Comment by sontek** [comment] 2012-08-15 15:24
Yeah, if it was easy to override that would be perfect.   The context i'm passing are lists of SQLAlchemy objects, so if the values in the database are null then the value set on the resulting property is None.    I can't really have the value not there.

**Comment by cjerdonek** [comment] 2012-08-15 15:36
In the meantime, can you do a preprocessing step that "sanitizes" the data and sets `None`'s to `''`?

**Comment by sontek** [comment] 2012-08-19 18:18
I created a new pull request, #132, makes it so you can override a context easily and do whatever you want with it.  It maintains complete backwards compatibility so nothing will break, it just allows me to make things match with mustache.js

**Comment by sontek** [comment] 2012-08-22 01:44
@cjerdonek  Is #132 good enough for you? It works perfectly for what I need and doesn't break the current usage

**Comment by cjerdonek** [comment] 2012-08-22 02:17
I want to sit down soon to think about the API change -- planning for this weekend.  I'm not crazy about adding another keyword argument to the Renderer constructor because that could easily get out of hand, and this is a somewhat specialized need.  Alternatives I would like to consider include: having a method that can be overridden on the Renderer class, exposing an undocumented or tentative API change that we could adjust later if need be, or perhaps support setting the context class to use as an attribute of some module.

The other implication of this change is that if we start supporting custom context classes, then we are also nailing down the context class interface, which hasn't really been thought through.  It was designed more as an internal class (i.e. more of an implementation detail).  So things could start getting more brittle if we go this route.

**Comment by cjerdonek** [comment] 2012-10-17 08:51
Retitled from "Differences between pystache and mustache.js" to "Allow None context value to render as empty string."

**Comment by cjerdonek** [comment] 2012-10-20 18:24
Thanks for your patience.  I committed a fix for this in the development branch.

I chose to address this in the Renderer class rather than in the Context class because how a context value renders is a rendering issue rather than something that the Context class should know about.

**Closed as completed by cjerdonek** 2012-10-20 18:24 UTC
