### ISSUE TITLE
Mustache(5) example not working

### ISSUE THREAD

**Issue by fidanov** [defunkt/pystache#26] opened 2011-07-08 11:11 UTC
Template:

{{#person?}}
  Hi {{name}}!
{{/person?}}

Dictinary:
{
  "person?": { "name": "Jon" }
}

Crashes -> this also does not work in the javascript version, I will submit a bug there also.

**Comment by cjerdonek** [comment] 2011-12-24 09:00
It looks like this is a duplicate of issue #15, which has been closed.  See the comments there for more information and the resolution.

**Closed as completed by cjerdonek** 2011-12-24 09:00 UTC
