### ISSUE TITLE
Changing delimiters should only affect the upcoming text.

### ISSUE THREAD

**Issue by lucasb-eyer** [defunkt/pystache#91] opened 2012-02-29 08:45 UTC
I am not sure if/how this issue relates to issue #84

using the dataset `{"a":"a", "b":"b", "c":"c", "d":"d", "e":"e", "f":"f"}`

The following:

```
<%a%>
{{b}}
{{=<% %>=}}
<%c%>
{{d}}
<%={{ }}=%>
{{e}}
<%f%>
```

Should result in:

```
<%a%>
b
c
{{d}}
e
<%f%>
```

But it actually results in:

```
a
b
c
d
e
<%f%>
```

This is very bad if you want to use both server-side and clien-side templates within one file. I checked the code and couldn't think of a quick-fix because this bug is inherent in the way the parser works: just search the whole template for the first match to a regex, replace this match then restart, from the beginning. It would rather need to restart from the previous match position.

**Comment by cjerdonek** [comment] 2012-02-29 11:23
This is possibly a duplicate of issue #35, which has been fixed in the development branch.  See this [test case](https://github.com/defunkt/pystache/blob/32adefb9c06627e228e8fc2de1b4b5cae4f800a5/tests/test_renderengine.py#L415), for example.  Just to be sure, I'll try to confirm that the example in the original comment above works in the development branch.

**Comment by cjerdonek** [comment] 2012-02-29 11:30
Yes, the test case presented in the original comment above works as expected in the development branch:

```
>>> import pystache
>>> context = {"a":"a", "b":"b", "c":"c", "d":"d", "e":"e", "f":"f"}
>>> template = """<%a%>
... {{b}}
... {{=<% %>=}}
... <%c%>
... {{d}}
... <%={{ }}=%>
... {{e}}
... <%f%>"""
>>> print pystache.render(template, context)
<%a%>
b
c
{{d}}
e
<%f%>
>>> 
```

**Closed as completed** 2012-02-29 11:37 UTC
